// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​e​a​r​n​ ​e​v​e​r​y​t​h​i​n​g​ ​a​b​o​u​t​ ​t​h​e
	 */
	MAIN_HEADING_1: string
	/**
	 * F​l​o​w​ ​B​l​o​c​k​c​h​a​i​n
	 */
	MAIN_HEADING_2: string
}

export type TranslationFunctions = {
	/**
	 * Learn everything about the
	 */
	MAIN_HEADING_1: () => LocalizedString
	/**
	 * Flow Blockchain
	 */
	MAIN_HEADING_2: () => LocalizedString
}

export type Formatters = {}
