import { ContentTypeEnum } from '$lib/types/content/metadata/content-types.enum';
import { SubjectsEnum } from '$lib/types/content/metadata/subject.enum';
import type { SnippetOverview } from '$lib/types/content/snippet.interface';

export const overview: SnippetOverview = {
  title: 'Account Linking - Redeem a Child Account',
  contentType: ContentTypeEnum.Snippet,
  author: {
    name: 'Jacob Tucker',
    socialMediaUrl: 'https://twitter.com/jacobmtucker',
    avatarUrl: 'https://avatars.githubusercontent.com/u/15198786?v=4',
    isVerified: true,
    walletAddress: '0x99bd48c8036e2876'
  },
  excerpt: 'Learn how to redeem a child account for account linking.',
  metadata: {
    subjects: [SubjectsEnum.Cadence]
  },
  codeLink: 'https://run.ecdao.org/?code=aW1wb3J0IEh5YnJpZEN1c3RvZHkgZnJvbSAweGQ4YTdlMDVhN2FjNjcwYzAKCmltcG9ydCBDYXBhYmlsaXR5RmFjdG9yeSBmcm9tIDB4ZDhhN2UwNWE3YWM2NzBjMAppbXBvcnQgQ2FwYWJpbGl0eUZpbHRlciBmcm9tIDB4ZDhhN2UwNWE3YWM2NzBjMAoKaW1wb3J0IE1ldGFkYXRhVmlld3MgZnJvbSAweDFkN2U1N2FhNTU4MTc0NDgKCnRyYW5zYWN0aW9uKGNoaWxkQWRkcmVzczogQWRkcmVzcywgbmFtZTogU3RyaW5nLCBkZXNjcmlwdGlvbjogU3RyaW5nLCB0aHVtYm5haWxVUkw6IFN0cmluZykgewogICAgcHJlcGFyZShhY2N0OiBBdXRoQWNjb3VudCkgewogICAgICAgIGlmIGFjY3QuYm9ycm93PCZIeWJyaWRDdXN0b2R5Lk1hbmFnZXI%2BKGZyb206IEh5YnJpZEN1c3RvZHkuTWFuYWdlclN0b3JhZ2VQYXRoKSA9PSBuaWwgewogICAgICAgICAgICBsZXQgbSA8LSBIeWJyaWRDdXN0b2R5LmNyZWF0ZU1hbmFnZXIoZmlsdGVyOiBuaWwpCiAgICAgICAgICAgIGFjY3Quc2F2ZSg8LSBtLCB0bzogSHlicmlkQ3VzdG9keS5NYW5hZ2VyU3RvcmFnZVBhdGgpCgogICAgICAgICAgICBhY2N0LnVubGluayhIeWJyaWRDdXN0b2R5Lk1hbmFnZXJQdWJsaWNQYXRoKQogICAgICAgICAgICBhY2N0LnVubGluayhIeWJyaWRDdXN0b2R5Lk1hbmFnZXJQcml2YXRlUGF0aCkKCiAgICAgICAgICAgIGFjY3QubGluazwmSHlicmlkQ3VzdG9keS5NYW5hZ2Vye0h5YnJpZEN1c3RvZHkuTWFuYWdlclByaXZhdGUsIEh5YnJpZEN1c3RvZHkuTWFuYWdlclB1YmxpY30%2BKEh5YnJpZEN1c3RvZHkuTWFuYWdlclByaXZhdGVQYXRoLCB0YXJnZXQ6IEh5YnJpZEN1c3RvZHkuTWFuYWdlclN0b3JhZ2VQYXRoKQogICAgICAgICAgICBhY2N0Lmxpbms8Jkh5YnJpZEN1c3RvZHkuTWFuYWdlcntIeWJyaWRDdXN0b2R5Lk1hbmFnZXJQdWJsaWN9PihIeWJyaWRDdXN0b2R5Lk1hbmFnZXJQdWJsaWNQYXRoLCB0YXJnZXQ6IEh5YnJpZEN1c3RvZHkuTWFuYWdlclN0b3JhZ2VQYXRoKQogICAgICAgIH0KCiAgICAgICAgbGV0IGluYm94TmFtZSA9IEh5YnJpZEN1c3RvZHkuZ2V0Q2hpbGRBY2NvdW50SWRlbnRpZmllcihhY2N0LmFkZHJlc3MpCiAgICAgICAgbGV0IGNhcCA9IGFjY3QuaW5ib3guY2xhaW08Jkh5YnJpZEN1c3RvZHkuQ2hpbGRBY2NvdW50e0h5YnJpZEN1c3RvZHkuQWNjb3VudFByaXZhdGUsIEh5YnJpZEN1c3RvZHkuQWNjb3VudFB1YmxpYywgTWV0YWRhdGFWaWV3cy5SZXNvbHZlcn0%2BKGluYm94TmFtZSwgcHJvdmlkZXI6IGNoaWxkQWRkcmVzcykKICAgICAgICAgICAgPz8gcGFuaWMoImNoaWxkIGFjY291bnQgY2FwIG5vdCBmb3VuZCIpCgogICAgICAgIGxldCBtYW5hZ2VyID0gYWNjdC5ib3Jyb3c8Jkh5YnJpZEN1c3RvZHkuTWFuYWdlcj4oZnJvbTogSHlicmlkQ3VzdG9keS5NYW5hZ2VyU3RvcmFnZVBhdGgpCiAgICAgICAgICAgID8%2FIHBhbmljKCJtYW5hZ2VyIG5vIGZvdW5kIikKCiAgICAgICAgbWFuYWdlci5hZGRBY2NvdW50KGNhcDogY2FwKQoKICAgICAgICBsZXQgdGh1bWJuYWlsID0gTWV0YWRhdGFWaWV3cy5IVFRQRmlsZSh1cmw6IHRodW1ibmFpbFVSTCkKICAgICAgICBsZXQgZGlzcGxheSA9IE1ldGFkYXRhVmlld3MuRGlzcGxheShuYW1lOiBuYW1lLCBkZXNjcmlwdGlvbjogZGVzY3JpcHRpb24sIHRodW1ibmFpbDogdGh1bWJuYWlsKQogICAgICAgIG1hbmFnZXIuc2V0Q2hpbGRBY2NvdW50RGlzcGxheShhZGRyZXNzOiBjaGlsZEFkZHJlc3MsIGRpc3BsYXkpCiAgICB9Cn0%3D&network=mainnet&args=eyJjaGlsZEFkZHJlc3MiOiIweDEiLCJuYW1lIjoiTmFtZSB5b3VyIGNoaWxkIGFjY291bnQiLCJkZXNjcmlwdGlvbiI6IihPcHRpb25hbCkgLSBEZXNjcmliZSB5b3VyIGNoaWxkIGFjY291bnQiLCJ0aHVtYm5haWxVUkwiOiJodHRwczovL2F2YXRhcnMuZmxvd3R5LmlvLzYueC90aHVtYnMvcG5nP3NlZWQ9MHhBTllUSElOR1lPVVdBTlQifQ%3D%3D'
};
