export async function GET() {
    return new Response(
        `
        <?xml version="1.0" encoding="UTF-8" ?>
        <urlset
            xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
            xmlns:xhtml="https://www.w3.org/1999/xhtml"
            xmlns:mobile="https://www.google.com/schemas/sitemap-mobile/1.0"
            xmlns:news="https://www.google.com/schemas/sitemap-news/0.9"
            xmlns:image="https://www.google.com/schemas/sitemap-image/1.1"
            xmlns:video="https://www.google.com/schemas/sitemap-video/1.1"
        >
            <!-- <url> elements go here -->
            <url>
                <loc>https://academy.ecdao.org/en</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>1.00</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/catalog</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.80</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.80</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-challenges</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.80</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/quickstarts</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.80</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/catalog/courses/beginner-cadence</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.80</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/catalog/courses/beginner-dapp</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.80</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/catalog/roadmaps/cadence</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.80</priority>
            </url>
            <url>           
                <loc>https://academy.ecdao.org/en/catalog/cadence</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/catalog/dapp</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/catalog/courses/dance-and-grow-rich</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/catalog/courses/intermediate-cadence</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/1-hello-world</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/2-first-app</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/3-primitive-types</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/4-variables</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/5-transaction</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/6-scripts</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/7-argument-labels</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/8-if-else</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/9-arrays</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/10-dictionaries</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/11-optionals</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/12-optional-binding</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/13-structs</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/14-resources</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/15-interfaces</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/16-storing-resources</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/17-references</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/18-account-storage</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-by-example/19-capabilities</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-challenges/missing-royalties</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-challenges/simple-profile</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/cadence-challenges/example-challenge</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/quickstarts/0-hello-world</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/quickstarts/1-non-fungible-token</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/quickstarts/2-fungible-token</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/quickstarts/3-nft-minting</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/quickstarts/4-voting</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/quickstarts/5-multisign</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>
            <url>
                <loc>https://academy.ecdao.org/en/quickstarts/6-groups</loc>
                <lastmod>2023-05-30T18:16:23+00:00</lastmod>
                <priority>0.64</priority>
            </url>

        </urlset>`.trim(),
        {
            headers: {
                'Content-Type': 'application/xml'
            }
        }
    );
}
