import { ContentTypeEnum } from '$lib/types/content/metadata/content-types.enum';
import { SubjectsEnum } from '$lib/types/content/metadata/subject.enum';
import type { SnippetOverview } from '$lib/types/content/snippet.interface';

export const overview: SnippetOverview = {
  title: 'Get all User NBATopShot Moments',
  contentType: ContentTypeEnum.Snippet,
  author: {
    name: 'Jacob Tucker',
    socialMediaUrl: 'https://twitter.com/jacobmtucker',
    avatarUrl: '/avatars/jacob.jpeg',
    isVerified: true,
    walletAddress: '0x99bd48c8036e2876'
  },
  excerpt: 'Get all the moments a user has on NBATopShot.',
  metadata: {
    subjects: [SubjectsEnum.Cadence]
  },
  codeLink: 'https://run.ecdao.org/?code=aW1wb3J0IFRvcFNob3QgZnJvbSAweDBiMmEzMjk5Y2M4NTdlMjkKCnB1YiBmdW4gbWFpbih1c2VyOiBBZGRyZXNzKTogW01vbWVudERhdGFdIHsKICBsZXQgYXV0aEFjY291bnQ6IEF1dGhBY2NvdW50ID0gZ2V0QXV0aEFjY291bnQodXNlcikKICBsZXQgbW9tZW50Q29sbGVjdGlvbiA9IGF1dGhBY2NvdW50LmJvcnJvdzwmVG9wU2hvdC5Db2xsZWN0aW9uPihmcm9tOiAvc3RvcmFnZS9Nb21lbnRDb2xsZWN0aW9uKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPz8gcGFuaWMoIlVzZXIgZG9lcyBub3QgaGF2ZSBhIFRvcFNob3QgQ29sbGVjdGlvbiIpCgogIGxldCBhbnN3ZXI6IFtNb21lbnREYXRhXSA9IFtdCgogIGZvciBpZCBpbiBtb21lbnRDb2xsZWN0aW9uLmdldElEcygpIHsKICAgIGxldCBtb21lbnQ6ICZUb3BTaG90Lk5GVCA9IG1vbWVudENvbGxlY3Rpb24uYm9ycm93TW9tZW50KGlkOiBpZCkhCiAgICBsZXQgcGxheToge1N0cmluZzogU3RyaW5nfSA9IFRvcFNob3QuZ2V0UGxheU1ldGFEYXRhKHBsYXlJRDogbW9tZW50LmRhdGEucGxheUlEKSEKCiAgICBsZXQgbW9tZW50RGF0YTogTW9tZW50RGF0YSA9IE1vbWVudERhdGEoCiAgICAgIGlkOiBtb21lbnQuaWQsCiAgICAgIHM6IG1vbWVudC5kYXRhLnNlcmlhbE51bWJlciwKICAgICAgcDogcGxheVsiRnVsbE5hbWUiXSA%2FPyAiTi9BIiwgCiAgICAgIHQ6IHBsYXlbIlRlYW1BdE1vbWVudCJdID8%2FICJOL0EiLCAKICAgICAgZDogcGxheVsiRGF0ZU9mTW9tZW50Il0gPz8gIk4vQSIsIAogICAgICBwYzogcGxheVsiUGxheUNhdGVnb3J5Il0gPz8gIk4vQSIsCiAgICAgIHNuOiBUb3BTaG90LmdldFNldE5hbWUoc2V0SUQ6IG1vbWVudC5kYXRhLnNldElEKSEKICAgICkKICAgIGFuc3dlci5hcHBlbmQobW9tZW50RGF0YSkKICB9CgogIHJldHVybiBhbnN3ZXIKfQoKcHViIHN0cnVjdCBNb21lbnREYXRhIHsKICBwdWIgbGV0IGlkOiBVSW50NjQKICBwdWIgbGV0IHNlcmlhbE51bWJlcjogVUludDMyCiAgcHViIGxldCBwbGF5ZXI6IFN0cmluZwogIHB1YiBsZXQgdGVhbTogU3RyaW5nCiAgcHViIGxldCBkYXRlOiBTdHJpbmcKICBwdWIgbGV0IHBsYXlDYXRlZ29yeTogU3RyaW5nCiAgcHViIGxldCBzZXROYW1lOiBTdHJpbmcKCiAgaW5pdChpZDogVUludDY0LCBzOiBVSW50MzIsIHA6IFN0cmluZywgdDogU3RyaW5nLCBkOiBTdHJpbmcsIHBjOiBTdHJpbmcsIHNuOiBTdHJpbmcpIHsKICAgIHNlbGYuaWQgPSBpZAogICAgc2VsZi5zZXJpYWxOdW1iZXIgPSBzCiAgICBzZWxmLnBsYXllciA9IHAKICAgIHNlbGYudGVhbSA9IHQKICAgIHNlbGYuZGF0ZSA9IGQKICAgIHNlbGYucGxheUNhdGVnb3J5ID0gcGMKICAgIHNlbGYuc2V0TmFtZSA9IHNuCiAgfQp9&network=mainnet&args=eyJ1c2VyIjoiMHg1NjgwZmEwNzY0MmI1MDJhIn0%3D'
};
